# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-is-localizable}
  s.version = "1.0.0.rc1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Gamsjaeger (snusnu)"]
  s.date = %q{2010-05-20}
  s.email = %q{gamsnjaga@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG",
     "Gemfile",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "TODO",
     "VERSION",
     "dm-is-localizable.gemspec",
     "lib/dm-is-localizable.rb",
     "lib/dm-is-localizable/is/localizable.rb",
     "lib/dm-is-localizable/storage/language.rb",
     "lib/dm-is-localizable/storage/translation.rb",
     "spec/fixtures/item.rb",
     "spec/lib/rspec_tmbundle_support.rb",
     "spec/rcov.opts",
     "spec/shared/shared_examples_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/auto_migrate_spec.rb",
     "spec/unit/class_level_api_spec.rb",
     "spec/unit/instance_level_api_spec.rb",
     "spec/unit/is_localizable_spec.rb",
     "spec/unit/language_spec.rb",
     "spec/unit/translation_spec.rb",
     "tasks/changelog.rake",
     "tasks/ci.rake",
     "tasks/install.rake",
     "tasks/local_gemfile.rake",
     "tasks/metrics.rake",
     "tasks/spec.rake",
     "tasks/whitespace.rake",
     "tasks/yard.rake",
     "tasks/yardstick.rake"
  ]
  s.homepage = %q{http://github.com/snusnu/dm-is-localizable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Datamapper support for localization of content in multilanguage applications}
  s.test_files = [
    "spec/fixtures/item.rb",
     "spec/lib/rspec_tmbundle_support.rb",
     "spec/shared/shared_examples_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/auto_migrate_spec.rb",
     "spec/unit/class_level_api_spec.rb",
     "spec/unit/instance_level_api_spec.rb",
     "spec/unit/is_localizable_spec.rb",
     "spec/unit/language_spec.rb",
     "spec/unit/translation_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.0.0.rc1"])
      s.add_runtime_dependency(%q<dm-is-remixable>, ["~> 1.0.0.rc1"])
      s.add_runtime_dependency(%q<dm-validations>, ["~> 1.0.0.rc1"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
      s.add_development_dependency(%q<yard>, ["~> 0.5"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.0.0.rc1"])
      s.add_dependency(%q<dm-is-remixable>, ["~> 1.0.0.rc1"])
      s.add_dependency(%q<dm-validations>, ["~> 1.0.0.rc1"])
      s.add_dependency(%q<rspec>, ["~> 1.3"])
      s.add_dependency(%q<yard>, ["~> 0.5"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.0.0.rc1"])
    s.add_dependency(%q<dm-is-remixable>, ["~> 1.0.0.rc1"])
    s.add_dependency(%q<dm-validations>, ["~> 1.0.0.rc1"])
    s.add_dependency(%q<rspec>, ["~> 1.3"])
    s.add_dependency(%q<yard>, ["~> 0.5"])
  end
end

